modLoader = "kotlinforforge"
loaderVersion = "[3,)"
issueTrackerURL = "https://github.com/Lizard-Of-Oz/Inventorio"
license = "Custom"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "LizardOfOz"
description = "${mod_description}"
logoFile = "icon.png"
displayURL="https://github.com/Lizard-Of-Oz/Inventorio"

[[dependencies.inventorio]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,1.20)"
ordering = "NONE"
side = "BOTH"

[[dependencies.inventorio]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.inventorio]]
modId = "cloth_config"
mandatory = true
versionRange = "[7,)"
ordering = "NONE"
side = "CLIENT"